/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    JinButton: typeof import('jin-ui')['Button']
    JinInfiniteScroll: typeof import('jin-ui')['InfiniteScroll']
    JinInput: typeof import('jin-ui')['Input']
    JinTable: typeof import('jin-ui')['Table']
    JinTableColumn: typeof import('jin-ui')['TableColumn']
    JinTooltip: typeof import('jin-ui')['Tooltip']
  }
}
